### PR TITLE
Fix windows #5

### PR DESCRIPTION
**Pull request by blegat**
It seems that the issue was with this `NOSHORTS` option

### CODE REVIEW

**Comment by blegat** [comment]
On Windows 32 bits:

```
Problem LIN2A
Iter:  0 Ap: 0.00e+000 Pobj:  1.7129989e+003 Ad: 0.00e+000 Dobj:  0.0000000e+000 
Iter:  1 Ap: 1.00e+000 Pobj:  8.2000000e+001 Ad: 1.00e+000 Dobj:  1.1112447e+003 
Iter:  2 Ap: 1.00e+000 Pobj:  8.2000000e+001 Ad: 1.00e-002 Dobj:  1.1011470e+003 
Stuck at edge of primal feasibility, giving up.
```

Noooooo :'(

**Comment by blegat** [comment]
@EQt  Could you kill the appveyor's build for 45a9173d977f6d1f122375d4b2b678c04f11599e, it is looping for 10 minutes and prevents the build for this PR to start :-P

**Comment by EQt** [comment]
> `Stuck at edge of primal feasibility, giving up.`

This may also be related to a bug in `libblas`: I compiled the original `csdp` executable and tested on `soc.prob.1` (from our unit tests). Depending on which implementation you use (atlas, liblapack, or openblas), it gets stuck or completes without errors. Don't know, what to do with this strange behavior.

**Comment by blegat** [comment]
Which one works best of atlas, liblapack and openblas ?

**Comment by blegat** [comment]
On Windows 32 bits:

```
Problem SOC1
INFO: Writing problem to C:\Users\appveyor\.julia\v0.5\CSDP\test/soc.prob.1
Iter:  0 Ap: 0.00e+000 Pobj:  0.0000000e+000 Ad: 0.00e+000 Dobj:  0.0000000e+000 
Iter:  1 Ap: 1.00e+000 Pobj:  1.4348779e-001 Ad: 1.00e+000 Dobj:  4.0421557e+001 
Iter:  2 Ap: 1.00e+000 Pobj:  2.8851926e-001 Ad: 9.00e-001 Dobj:  4.3018215e+000 
Iter:  3 Ap: 1.00e+000 Pobj:  1.1383216e+000 Ad: 1.00e+000 Dobj:  3.1449719e+000 
Iter:  4 Ap: 1.00e+000 Pobj:  1.1841119e+000 Ad: 1.00e+000 Dobj:  2.1874361e+000 
Iter:  5 Ap: 1.00e+000 Pobj:  1.2811728e+000 Ad: 1.00e+000 Dobj:  1.7828340e+000 
Iter:  6 Ap: 1.00e+000 Pobj:  1.3400083e+000 Ad: 1.00e+000 Dobj:  1.5908381e+000 
Iter:  7 Ap: 1.00e+000 Pobj:  1.3748455e+000 Ad: 1.00e+000 Dobj:  1.5002595e+000 
Iter:  8 Ap: 1.00e+000 Pobj:  1.4142124e+000 Ad: 9.00e-001 Dobj:  1.4228155e+000 
Iter:  9 Ap: 1.00e+000 Pobj:  1.4142136e+000 Ad: 9.00e-001 Dobj:  1.4150722e+000 
Iter: 10 Ap: 1.00e+000 Pobj:  1.4142136e+000 Ad: 1.00e+000 Dobj:  1.4142118e+000 
Stuck at edge of primal feasibility, giving up.
```

Same issue :'(

**Comment by EQt** [comment]
Atlas and liblapack (as shipped with Ubuntu) seem fine. OpenBLAS (for both, Ubuntu and the version included in Julia, 64bit) gets stuck.

**Comment by blegat** [comment]
Win32 solves the two SDP test from MathProgBase juste fin :) but fails on LIN, SOC and SOCRotated which I have disabled for Win32 until we find a solution so that the tests pass on master.
We can reenable them in the PR that tries to find a solution.

**Comment by blegat** [comment]
I have finished this PR, you can review it :)

**Pull request merged**
